### ISSUE TITLE
Cannot click on "Task" (Tick mark) in iOS safari

### ISSUE THREAD

**Issue by kelvinkoko** [nhn/tui.editor#662] opened 2019-10-15 02:51 UTC
## Version
v1.4.7

## Test Environment
iOS safari

## Current Behavior
In WYSIWYG mode, when user is typing (showing keyboard)
for the "Task" item

- [ ]  

cannot not click on it to see the "Tick" mark

## Expected Behavior
After click on it should show tick-ed
- [x]

**Comment by seonim-ryu** [comment] 2019-10-18 02:22
@kelvinkoko 
I checked the issue. The editor doesn't fully support mobile but.. This issue seems to be caused by focus on mobile safari. I've tested it on version 13.1.2, iPhone XR, and the click behavior was different depending on the focus position.

The checkbox is not clicking when the focus is right behind the checkbox. The gap between the checkbox area and the next focus is too narrow, so the checkbox area is focused instead of being clicked.

* Correct behavior

![correct](https://user-images.githubusercontent.com/18183560/67060165-be345580-f196-11e9-8bb2-a77fd26de7ab.PNG)

* Wrong behavior

![wrong](https://user-images.githubusercontent.com/18183560/67060217-e0c66e80-f196-11e9-8681-183d007aefef.PNG)

If you are overriding the style of the editor, you might solve the problem by adjusting the spacing between the checkbox and the text that follows.

```css
.tui-editor-contents .task-list-item {
  padding-left: 22px; /* original value */
}
```
![style](https://user-images.githubusercontent.com/18183560/67060718-e6bd4f00-f198-11e9-9705-de123ee2f212.png)

Can you check it? :)

**Comment by kelvinkoko** [comment] 2019-10-21 04:10
@seonim-ryu Thank you for your investigation, you are right. I think it is the cause. 
Thanks for you guys great work and your support!~

**Comment by seonim-ryu** [comment] 2019-11-29 08:23
I'm closing this issue because it seems to be resolved.

**Closed by seonim-ryu** 2019-11-29 08:23 UTC
Labels: Category: List, Need Discussion, Question
