### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by YBHwang** [nhn/tui.editor#837] opened 2020-03-19 06:27 UTC
**Describe the bug**
`Uncaught TypeError: Cannot read property 'classList' of null`

**To Reproduce**
> I use only Native HTML, CSS, JAVASCRIPT
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.4/codemirror.min.css" />
    <link rel="stylesheet" href="https://uicdn.toast.com/editor/latest/toastui-editor.min.css" />
</head>
<body>
    <!-- ERROR -->
    <!--
    <form>
        <div id="editor"></div>
    </form>
    -->
    <div id="editor"></div>

    <script src="https://code.jquery.com/jquery-latest.min.js"></script>
    <script src="https://uicdn.toast.com/editor/latest/toastui-jquery-editor.min.js"></script>
    <!-- <script src="https://uicdn.toast.com/editor/latest/i18n/ko-kr.js"></script> -->
    <script>
        const option = {
            initialEditType: 'wysiwyg',
            height: '500px'
        };
        const editor = $('#editor').toastuiEditor(option);
    </script>
</body>
</html>
```

**Expected behavior**
> "I cannot use editor with wrapping by `<form>` tag"

**Screenshots**

> Console
```console
Uncaught TypeError: Cannot read property 'classList' of null
    at e.exports (toastui-jquery-editor.min.js:14)
    at r.i._updateClassByButton (toastui-jquery-editor.min.js:30)
    at r.i._activateTabByButton (toastui-jquery-editor.min.js:30)
    at r.i.activate (toastui-jquery-editor.min.js:30)
    at r.i._render (toastui-jquery-editor.min.js:30)
    at new r (toastui-jquery-editor.min.js:30)
    at r.i._initDOM (toastui-jquery-editor.min.js:30)
    at r [as constructor] (toastui-jquery-editor.min.js:30)
    at new r (toastui-jquery-editor.min.js:30)
    at e.t._initPopupAddImage (toastui-jquery-editor.min.js:30)
```
**Device Information -> SKIP**

**Additional context**

> I want to use `i18n` with JQuery. But I got error When I add script line in document, `ko-kr.js`

**Comment by NateScarlet** [comment] 2020-03-19 10:16
This is beacuse a form can not can have another form as child.

https://github.com/nhn/tui.editor/blob/7c50de827c3644a5033ea1b8f60b3cc78529d33d/apps/editor/src/js/ui/popupAddImage.js#L87
`fileTypeSection` will be null if  used in form.

maybe change `POP_CONTENT` to not use `form` element can fix this.

**Comment by seonim-ryu** [comment] 2020-03-23 04:08
@YBHwang First, the cause is what @NateScarlet said.

The editor uses a `form` tag to upload the image file, so if you wrap the editor wrapper element with a `form` tag in the way you use it, the structure is as follows:

```html
<form>
  <div id="editor">
    ...
    <form enctype="multipart/form-data" class="te-file-type">
      ...
    </form>
    ...
  </div>
</form>
```

But the [W3C spec](https://www.w3.org/MarkUp/html3/forms.html) says, you shouldn't use form tags overlapping. The editor should not remove a `form` tag used internally, so you should not wrap it around with a `form` tag.

> Every form must be enclosed within a FORM element. There can be several forms in a single document, but the FORM element can't be nested. 

Is there any reason you should write like this?

**Comment by seonim-ryu** [comment] 2020-03-23 04:33
@YBHwang And I have confirmed an error when using language files in the CDN of the jQuery wrapper. I will register and handle this issue separately.

**Comment by NateScarlet** [comment] 2020-03-23 05:07
> Is there any reason you should write like this?

I think submit markdown data with form is a common usecase.

**Comment by YBHwang** [comment] 2020-03-25 15:51
> @YBHwang First, the cause is what @NateScarlet said.
> 
> The editor uses a `form` tag to upload the image file, so if you wrap the editor wrapper element with a `form` tag in the way you use it, the structure is as follows:
> 
> ```
> <form>
>   <div id="editor">
>     ...
>     <form enctype="multipart/form-data" class="te-file-type">
>       ...
>     </form>
>     ...
>   </div>
> </form>
> ```
> 
> But the [W3C spec](https://www.w3.org/MarkUp/html3/forms.html) says, you shouldn't use form tags overlapping. The editor should not remove a `form` tag used internally, so you should not wrap it around with a `form` tag.
> 
> > Every form must be enclosed within a FORM element. There can be several forms in a single document, but the FORM element can't be nested.
> 
> Is there any reason you should write like this?

That's because `editor.getHtml();` or `editor.getMarkdown();` is not working at JQuery Edition

**Comment by seonim-ryu** [comment] 2020-03-26 01:16
@YBHwang Have you ever used `editor.getHtml()` like this? If you use jQuery wrapper you shouldn't use it like that. Would you like to call the function as below?
```js
const $editor = $('#editor');

// create instance
$editor.toastuiEditor({
  // ...
});

// call instance methods
const markdown = $editor.toastuiEditor('getMarkdown');
const html = $editor.toastuiEditor('getHtml');

console.log(markdown);
console.log(html);
```
![jquery-wrapper](https://user-images.githubusercontent.com/18183560/77600259-aed9e500-6f4a-11ea-99e2-1755ef607623.png)

**Comment by YBAZAN** [comment] 2020-03-31 16:14
Hi, I have the same issue when I put the editor inside a modal with a form. But I do not use the jquery wrapper version. And I'm even not interested to use the image tool, but it seems we cannot deactivate it.

How can we handle this problem ?

**Comment by seonim-ryu** [comment] 2020-04-06 01:29
@YBAZAN As I replied [here](https://github.com/nhn/tui.editor/issues/837#issuecomment-602374237), wrapping up the form causes such an issue. How about getting the editor value using `editor.getHtml()`, `editor.getMarkdown()` API and then sending the form data?

**Comment by YBAZAN** [comment] 2020-04-06 08:11
> @YBAZAN As I replied [here](https://github.com/nhn/tui.editor/issues/837#issuecomment-602374237), wrapping up the form causes such an issue. How about getting the editor's value using `editor.getHtml()`, `editor.getMarkdown()` API and then sending the form data?

Thanks for your answer. I would like to add 2 points:
- In my app, the editor is a field inside a form (in a modal in most of cases) containing others inputs. I cannot extract it outside the form. It would break the layout. 
- There is no issue with the 1.4.10 version. Is it a design change in v2 or was this problem present in previous versions but not visible?

**Comment by HisDudedness** [comment] 2020-04-07 06:30
I am embedding the editor in [wicket](https://wicket.apache.org/) forms, which worked well with v1.4.10 and breaks in v2 due to the form tag. Moving the editor out of the forms is not easy (if possible at all) and makes the editor less versatile to use. 
I wonder if it really must be a form in the image upload? (As a quick and dirty experiment I changed the form to a div and files are still inserted.)

**Comment by js87zz** [comment] 2020-04-07 08:06
@YBHwang @HisDudedness @NateScarlet 
We checked the `form` tag(legacy code) in our editor and concluded that it doesn't matter if it is eliminated because internal `form` is not submitted and used anywhere. So, It will be replaced to `div` tag. I think the jquery prevented this error in `v1.x`, but the error occurred after removing jquery dependency in `v2.x`.
Thank you!

**Comment by HisDudedness** [comment] 2020-04-07 08:25
Great news! Thanks!

**Comment by mieszko4** [comment] 2020-04-07 12:17
Thnx for fixing, looking forward for the release!

Because this error happened to me when using react wrapper `<Editor` inside `<Formik`

**Comment by YBAZAN** [comment] 2020-04-10 07:54
Thank you !

Do you havea release date for this fix ?

**Comment by gowda-nirmal** [comment] 2020-04-15 19:48
> Because this error happened to me when using react wrapper `<Editor` inside `<Formik`

@mieszko4 - I am facing the same issue in react wrapper. Can you let me know how you resolved this issue?

**Comment by mieszko4** [comment] 2020-04-15 20:27
@gowda-nirmal https://github.com/nhn/tui.editor/pull/890 is merged but looks like it is not released yet (https://github.com/nhn/tui.editor/releases)

**Comment by seonim-ryu** [comment] 2020-04-16 02:37
@YBAZAN @gowda-nirmal @mieszko4 The npm release will be done later this month.

**Comment by landall** [comment] 2020-04-19 08:12
I face the same issue, too.
Maybe the component should use two DOM element to handle this thing.
one to create a inner form, the other to show the editor/viewer.

**Comment by Yash-GitB** [comment] 2020-04-26 20:25
@seonim-ryu Any updates on when this release is for React?

**Comment by seonim-ryu** [comment] 2020-04-29 11:26
@landall @Yash-GitB 
The [2.1.0 version has been released](https://github.com/nhn/tui.editor/releases/tag/v2.1.0) and the wrappers have also been updated with the Editor.

So I'll close this issue. If you have any problems, please register a new issue. :)

**Closed** 2020-04-29 11:26 UTC
Labels: Question, Wrapper: jQuery
