### ISSUE TITLE
TypeError: Cannot read property 'match' of null

### ISSUE THREAD

**Issue by silinchen** [nhn/tui.editor#1608] opened 2021-06-26 15:37 UTC
## Describe the bug

TypeError: Cannot read property 'match' of null
Plugin.keyup
node_modules/@toast-ui/editor/dist/esm/index.js:3827
  3824 | var paraNode = findClosestNode(mdNode, function (node) { var _a; return node.type === 'paragraph' && ((_a = node.parent) === null || _a === void 0 ? void 0 : _a.type) === 'item'; });
  3825 | if (paraNode && paraNode.firstChild) {
  3826 |     var firstChild = paraNode.firstChild;
> 3827 |     var matched = firstChild.literal.match(reTaskMarker);
       | ^  3828 |     if (matched) {
  3829 |         var startMdPos = firstChild.sourcepos[0];
  3830 |         var startSpaces = matched[1], stateChar = matched[2], lastSpaces = matched[3];

when you type the flow code, the error was emit.

-  *123*

(-spacespace*123*)

and delete the second space, the error was happen

**Comment by silinchen** [comment] 2021-06-26 15:39
`-  *123*`

**Comment by js87zz** [comment] 2021-06-30 04:56
@silinchen 
Can you explain more detail? I cannot reproduce it.

**Comment by silinchen** [comment] 2021-07-09 02:27
> @silinchen
> Can you explain more detail? I cannot reproduce it.

![image](https://user-images.githubusercontent.com/17904619/125014275-f46ae480-e09f-11eb-86f7-c2731e00e957.png)
![image](https://user-images.githubusercontent.com/17904619/125014434-49a6f600-e0a0-11eb-81f0-de67a68fa6bc.png)

**Comment by js87zz** [comment] 2021-07-09 03:12
@silinchen 
I will fix it. Thanks!

**Comment by js87zz** [comment] 2021-08-05 01:20
@silinchen 
The bug has been fixed in `v3.0.2`. Thanks!

**Closed by js87zz** 2021-08-05 01:20 UTC
Labels: Bug
